#!/bin/bash

echo "Registering new books..."
find . -type f -not -name 000-browse.php -not -name md5sums.txt -not -name update-md5 -not -name .htaccess \
             -not -name header.html -not -name exclude.txt -not -name .updateme \
             -not -path './urantia-library/*' -not -path '*/*.html' -not -path './Incoming/*' -not -path './.authors/*' -not -path '*/*.sdr/*' -not -path './Websites/*' -not -path '*/.covers*' \
             -not -name nexus10.exclude -not -exec fgrep -q {} md5sums.txt \;  -exec md5sum {} + | \
    tee -a md5sums.txt

echo "Checking for duplicates..."
dups=$(awk -F' ' '{print $1}' md5sums.txt |sort|uniq -d)
for dup in $dups
do
   grep $dup md5sums.txt
done

#tree -D --dirsfirst -h --du -F \
#     -I "Websites|tree-index.html|update-md5|f|exclude.txt|urantia-library" \
#     -C -T "URANTIA LIBRARY ($(date))" --charset utf-8 -H . -o tree-index.html
